-- MySQL Script generated by MySQL Workbench
-- Wed Dec 18 11:51:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema my_hotel_reservation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema my_hotel_reservation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_hotel_reservation` DEFAULT CHARACTER SET utf8 ;
USE `my_hotel_reservation` ;

-- -----------------------------------------------------
-- Table `my_hotel_reservation`.`Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_hotel_reservation`.`Hotel` (
  `hotel_id` INT NOT NULL AUTO_INCREMENT,
  `hotel_name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `price` VARCHAR(45) NULL,
  `room_cnt` INT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` VARCHAR(45) NOT NULL,
  `updated_at` DATETIME NULL,
  `updated_by` VARCHAR(45) NULL,
  `deleted_at` DATETIME NULL,
  `deleted_by` VARCHAR(45) NULL,
  `del_flg` CHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`hotel_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_hotel_reservation`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_hotel_reservation`.`Customer` (
  `cust_id` INT NOT NULL AUTO_INCREMENT,
  `cust_name` VARCHAR(45) NULL,
  `cust_address` VARCHAR(45) NULL,
  `cust_mobile` VARCHAR(45) NULL,
  PRIMARY KEY (`cust_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_hotel_reservation`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_hotel_reservation`.`reservation` (
  `reserv_id` INT NOT NULL AUTO_INCREMENT,
  `hotel_id` INT NOT NULL,
  `cust_id` INT NOT NULL,
  `persons` TINYINT(2) NULL,
  `checkin` VARCHAR(10) NULL,
  `checkout` VARCHAR(10) NULL,
  `arrive_date` DATETIME NULL,
  `departure_date` DATETIME NULL,
  `payment` VARCHAR(45) NULL,
  `amount` DECIMAL NULL,
  `pre_paid` DECIMAL NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`reserv_id`, `hotel_id`, `cust_id`),
  INDEX `fk_reservation_Hotel_idx` (`hotel_id` ASC) VISIBLE,
  INDEX `fk_reservation_Customer1_idx` (`cust_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_Hotel`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `my_hotel_reservation`.`Hotel` (`hotel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_Customer1`
    FOREIGN KEY (`cust_id`)
    REFERENCES `my_hotel_reservation`.`Customer` (`cust_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
