Vagrant.configure("2") do |config|
  config.vm.define:"Node01" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.provider:virtualbox do |vb|
        vb.name="Node01"
    end
    cfg.vm.host_name="node01"
    cfg.vm.network "public_network", ip: "192.168.56.101"
    cfg.vm.network "forwarded_port", guest: 3306, host: 13306, auto_correct: false, id: "ssh"
    cfg.vm.provision "shell", path: "bash_ssh_conf.sh"
  end
end