Vagrant.configure("2") do |config|
  # Node01
  config.vm.define:"node01" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.provider:virtualbox do |vb|
        vb.name="Node01"
        vb.customize ["modifyvm", :id, "--cpus", 1]
        vb.customize ["modifyvm", :id, "--memory", 1024]
    end
    cfg.vm.host_name="node01"
    cfg.vm.synced_folder "./data", "/home/vagrant/data"
    cfg.vm.network "public_network", ip: "192.168.56.11"
    cfg.vm.network "forwarded_port", guest: 22, host: 19211, auto_correct: false, id: "ssh"
    cfg.vm.network "forwarded_port", guest: 80, host: 10080
    cfg.vm.network "forwarded_port", guest: 3306, host: 13306
  end

  # Node02
  config.vm.define:"node02" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.provider:virtualbox do |vb|
        vb.name="Node02"
        vb.customize ["modifyvm", :id, "--cpus", 1]
        vb.customize ["modifyvm", :id, "--memory", 1024]
    end
    cfg.vm.host_name="node02"
    cfg.vm.network "public_network", ip: "192.168.56.12"
    cfg.vm.network "forwarded_port", guest: 22, host: 29211, auto_correct: false, id: "ssh"
    cfg.vm.network "forwarded_port", guest: 80, host: 20080
    cfg.vm.network "forwarded_port", guest: 3306, host: 23306
  end
  # Node03
  config.vm.define:"node03" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.provider:virtualbox do |vb|
        vb.name="Node03"
        vb.customize ["modifyvm", :id, "--cpus", 1]
        vb.customize ["modifyvm", :id, "--memory", 1024]
    end
    cfg.vm.host_name="node03"
    cfg.vm.network "public_network", ip: "192.168.56.13"
    cfg.vm.network "forwarded_port", guest: 22, host: 39211, auto_correct: false, id: "ssh"
    cfg.vm.network "forwarded_port", guest: 80, host: 30080
    cfg.vm.network "forwarded_port", guest: 3306, host: 33306
  end
end